
# Check session (dev endpoint)
GET http://localhost:5000/session

###

# Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Bob",
    "email": "bob-the-builder@gmail.com",
    "password" : "fixNotBrake22"
}

###

# Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob-the-builder@gmail.com",
    "password": "fixNotBrake22"
}

###

# Logout
GET http://localhost:5000/auth/logout

###

# Dashboard
GET http://localhost:5000/dashboard

###

# Check auth
GET http://localhost:5000/auth/check-auth